
function App() {
  return (
      <>
        <div className={"main"} role={"main"}>
            <div className={"container"}>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
                <div>MAIN</div>
            </div>
        </div>
      </>
  );
}

export default App;
